name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Build the Docker image        
      run: docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --tag ${{ secrets.DOCKER_USER }}/smp-server:$(date +%Y).$(date +%m) . --file Dockerfile
      
    - name: Tag as latest
      run: docker tag ${{ secrets.DOCKER_USER }}/smp-server:$(date +%Y).$(date +%m) ${{ secrets.DOCKER_USER }}/smp-server:latest

    - name: Push the image
      run: docker push ${{ secrets.DOCKER_USER }}/smp-server:$(date +%Y).$(date +%m)

    - name: Push the image (latest)
      run: docker push ${{ secrets.DOCKER_USER }}/smp-server:latest
